### ISSUE TITLE
Add GFF as an output format

### ISSUE THREAD

**Issue by s-andrews** [s-andrews/nexons#3]
We're currently using a custom tab delimited format to output the quantitated structures from nexons, but for inter-operability it would be useful to have a more standard format which would load into something like IGV.

GFF would seem to be the obvious answer.  All of the information we'd need is available for this and it has a 'score' field which could hold the count value.

We'd want to output a transcript feature which held the counts, and then exon features to show the structure.

We could use either GFF or GTF depending on how formal we wanted to be.

**Comment by laurabiggins** [comment]
This has been implemented, and gtf output can be selected by using the --gtf_out flag, or the --both_out flag to obtain the default nexons output as well as gtf output.
